openapi: 3.0.1
info:
  title: Mc-Shop
  version: 1.0.0
externalDocs:
  description: View on GitHub
  url: https://github.com/Ubunfu/mc-shop
tags:
- name: shop
  description: Shop Operations
paths:
  /item:
    get:
      tags:
        - shop
      summary: Get one item available for sale
      operationId: getItem
      parameters: 
        - name: search
          in: query
          description: URL-encoded search terms for shop items
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemResp'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResp'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResp'
  /items:
    get:
      tags:
        - shop
      summary: Get all items available for sale
      operationId: getItems
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemsResp'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResp'
  /items/search:
    get:
      tags:
        - shop
      summary: Search for items available for sale.  Returns just a few items.
      operationId: searchItems
      parameters: 
        - name: search
          in: query
          description: URL-encoded search terms for shop items
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemsResp'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResp'
  /buyItem:
    post:
      tags:
        - shop
      summary: Purchase an item from the shop
      operationId: buyItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BuyRequest'
        required: true
      responses:
        200:
          description: OK
        400:
          description: Invalid Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResp'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResp'
  /sellItem:
    post:
      tags:
        - shop
      summary: Sell an item to the shop
      operationId: sellItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SellRequest'
        required: true
      responses:
        200:
          description: OK
        400:
          description: Invalid Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResp'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResp'
components:
  schemas:
    ItemResp:
      type: object
      properties:
        itemName: 
          type: string
        price:
          type: string
    ItemsResp:
      type: array
      items:
        type: object
        properties:
          itemName:
            type: string
          price:
            type: integer
    ErrorResp:
      type: object
      properties:
        error:
          type: string
        errorDetail:
          type: string
    BuyRequest:
      type: object
      properties:
        player:
          type: string
        itemName:
          type: string
        quantity:
          type: integer
    SellRequest:
      type: object
      properties:
        player:
          type: string
        itemName:
          type: string
        quantity:
          type: integer
